# Generated by Django 5.1.3 on 2025-12-07 09:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(default='count', max_length=20)),
                ('dose', models.CharField(max_length=100)),
                ('timing', models.CharField(blank=True, max_length=20, null=True)),
                ('food_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('is_given_today', models.BooleanField(default=False)),
                ('given_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.patient')),
            ],
            options={
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='api.patient')),
            ],
            options={
                'db_table': 'daily_record',
                'constraints': [models.UniqueConstraint(fields=('patient', 'date'), name='unique_patient_date')],
            },
        ),
    ]
